name: Newline Test

on:
  push:
    branches:
      - newline-test

jobs:
  jobA:
    runs-on: ubuntu-latest

    steps:
      - name: Print List
        env:
          MY_LIST: |
            "a"
            "b"
            "c"
        run: |
          echo "$MY_LIST"
        shell: bash
      - name: Loop List
        env:
          MY_LIST: |
            "a"
            "b"
            "c"
        run: |
          for tag in "${{ env.MY_LIST }}"; do
            echo "$tag"
          done
        shell: bash
